### ISSUE TITLE
缺失《汉译图表》

### ISSUE THREAD

**Issue by MudroadWhite** [linonetwo/yaba-japanese#1]
在一段阅读以后发现《汉译图表》是对里面内容进行讲解很重要的东西，包括矢波总句貌似也写在这张图表里面。readme里面貌似没有提到这一点，还是说我阅读得不够仔细？

**Comment by linonetwo** [comment]
嗯，那是一个塑封的彩页，好像没有扫进来，我问问知乎答主那个彩页还在不在

**Comment by linonetwo** [comment]
害 原书的主人很久以前就搞丢了，湮灭在历史的长河中了。

**Comment by linonetwo** [comment]
<img width="704" alt="截屏2020-09-21 下午7 40 39" src="https://user-images.githubusercontent.com/3746270/93762571-6f166080-fc42-11ea-9a60-71e048a7f5af.png">

我上传放到仓库首页了。
